// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYZeyDbQ_SLnH-ruVpQC2y8SHOtC6-L0',
    appId: '1:689799503252:web:2c3a433af0f917effd0381',
    messagingSenderId: '689799503252',
    projectId: 'arhibu-b4c74',
    authDomain: 'arhibu-b4c74.firebaseapp.com',
    storageBucket: 'arhibu-b4c74.firebasestorage.app',
    measurementId: 'G-YMMBLF9W1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehickY_zNlTOdbnuyPPD2ber-P2GBYrQ',
    appId: '1:689799503252:android:cbd92a4a52c4522bfd0381',
    messagingSenderId: '689799503252',
    projectId: 'arhibu-b4c74',
    storageBucket: 'arhibu-b4c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzRLcBfzU81Jni04BvvV9VLz9brCTdXk',
    appId: '1:689799503252:ios:f85cc14907d1e953fd0381',
    messagingSenderId: '689799503252',
    projectId: 'arhibu-b4c74',
    storageBucket: 'arhibu-b4c74.firebasestorage.app',
    iosBundleId: 'com.example.arhibu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzRLcBfzU81Jni04BvvV9VLz9brCTdXk',
    appId: '1:689799503252:ios:f85cc14907d1e953fd0381',
    messagingSenderId: '689799503252',
    projectId: 'arhibu-b4c74',
    storageBucket: 'arhibu-b4c74.firebasestorage.app',
    iosBundleId: 'com.example.arhibu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYZeyDbQ_SLnH-ruVpQC2y8SHOtC6-L0',
    appId: '1:689799503252:web:c51f8b1aebdf5e59fd0381',
    messagingSenderId: '689799503252',
    projectId: 'arhibu-b4c74',
    authDomain: 'arhibu-b4c74.firebaseapp.com',
    storageBucket: 'arhibu-b4c74.firebasestorage.app',
    measurementId: 'G-V5XRR3EGWQ',
  );

}